"""empty message

Revision ID: 258d94e30e2f
Revises: 
Create Date: 2021-12-26 19:43:20.741542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258d94e30e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line_1', sa.String(length=64), nullable=False),
    sa.Column('address_line_2', sa.String(length=64), nullable=True),
    sa.Column('address_line_3', sa.String(length=64), nullable=True),
    sa.Column('address_line_4', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.Integer(), nullable=True),
    sa.Column('branch_name', sa.String(length=64), nullable=True),
    sa.Column('branch_address_line_1', sa.String(length=64), nullable=False),
    sa.Column('branch_address_line_2', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.String(length=6), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('micr', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_code')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cbs_cif', sa.String(length=12), nullable=True),
    sa.Column('salutation', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=32), nullable=True),
    sa.Column('father_husband_name', sa.String(length=128), nullable=True),
    sa.Column('mother_name', sa.String(length=128), nullable=True),
    sa.Column('uidai_no', sa.String(length=12), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('driving_licence', sa.String(length=32), nullable=True),
    sa.Column('voter_id', sa.String(length=32), nullable=True),
    sa.Column('passport', sa.String(length=32), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cbs_cif'),
    sa.UniqueConstraint('driving_licence'),
    sa.UniqueConstraint('pan_no'),
    sa.UniqueConstraint('uidai_no'),
    sa.UniqueConstraint('voter_id')
    )
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('roll_no', sa.Integer(), nullable=True),
    sa.Column('branch_code', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['branch_code'], ['branch.branch_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_no')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_employee_name'), 'user', ['employee_name'], unique=False)
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('email_type', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=True),
    sa.Column('mobile_number_type', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobile_number')
    op.drop_table('email')
    op.drop_index(op.f('ix_user_employee_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('branch')
    op.drop_table('address')
    # ### end Alembic commands ###
